version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=sanjeev
      - POSTGRES_PASSWORD=sanjeevemail
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
